# Generated by Django 3.2 on 2024-08-07 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240807_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator], verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.SlugField(max_length=150, unique=True, verbose_name='username пользователя'),
        ),
    ]
