# Generated by Django 3.2 on 2024-08-08 14:26

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240807_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator, users.validators.validate_email], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=150, validators=[users.validators.check_role_exists], verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator, users.validators.validate_username], verbose_name='username пользователя'),
        ),
    ]
